services:
  app:
    build: .
    image: ${DOCKERHUB_USERNAME}/medicareflow-api:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.medicareflow.loadbalancer.server.port=8080"

      - "traefik.http.routers.medicareflow-public.rule=Host(`api.suissetiawan.my.id`) && PathPrefix(`/medicareflow`)"
      - "traefik.http.routers.medicareflow-public.entrypoints=web"
      - "traefik.http.routers.medicareflow-local.rule=Host(`api.suissetiawan.home`) && PathPrefix(`/medicareflow`)"
      - "traefik.http.routers.medicareflow-local.entrypoints=web"

    container_name: api-medicareflow
    ports:
      - "8081:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - financial-tracker-network

networks:
  financial-tracker-network:
    name: financial-tracker-network
