spring.application.name=medicareflow

# JPA Configuration
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Pageable Configuration
spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.pageable.default-page-size=10

# Cron Slot Generation
app.slot.generation-cron=0 0 0 * * *
app.update.appointment.cron=0 0/2 * * * *

# Swagger Configuration
springdoc.swagger-ui.path=/docs/swagger-ui.html
springdoc.api-docs.path=/docs/api-docs
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=none
springdoc.default-flat-param-object=true
springdoc.swagger-ui.persistAuthorization=true

